### ISSUE TITLE
0.3.0 release checklist

### ISSUE THREAD

**Issue by yallop** [dsheets/ocaml-unix-sys-stat#6]
* [x] Add a more detailed [README][README] (#10)
* [x] Review the interface for consistency and completeness (#9)
* [x] Bring the authors list up to date (9e768ef)
* [x] Update the [changelog][changelog] (38751ab7)
* [x] Check the build with and without optional dependencies
* [x] Update version numbers
* [x] Tag ([0.3.0](https://github.com/dsheets/ocaml-unix-sys-stat/tree/0.3.0))
* [x] Publish on [opam-repository][opam-repository] (https://github.com/ocaml/opam-repository/pull/6264)

[README]: https://github.com/dsheets/ocaml-unix-dirent/blob/master/README.md
[changelog]: https://github.com/dsheets/ocaml-unix-dirent/blob/master/CHANGES
[opam-repository]: https://github.com/ocaml/opam-repository/
